<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRdZ6bI5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRdZ6bI5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRdZ6bI5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRdZ6bI5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRdZ6bI5\App_KernelDevDebugContainer([
    'container.build_hash' => 'RdZ6bI5',
    'container.build_id' => 'fb67675f',
    'container.build_time' => 1722416901,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRdZ6bI5');
